title: Dalek Mod Developer Wiki
description: Wiki for Dalek Mod addon developers
theme: just-the-docs
color_scheme: dark

favicon_ico: "images/favicon.ico"
logo: "images/icon.png"
url: https://jamesledolphin.github.io/dm-dev-wiki
